feat: add support for SnowyDirt on Plant
teaconmc/XKDeco pull request #24
Opened 2024-03-11 12:34 UTC by a1640727878

2024-03-11 22:50 UTC, Snownee requested changes

2024-03-11 22:50 UTC, Snownee commented on src/main/java/org/teacon/xkdeco/init/XKDecoObjects.java
> +				var block = BLOCKS.register(id, () -> new PlantSlabBlock(properties, isPath, "dirt_slab"));
某些方块应变为下界岩台阶。这里建议每个台阶单独注册（使用addBlock方法），不要用字符串匹配了

2024-03-11 22:50 UTC, Snownee commented on src/main/java/org/teacon/xkdeco/block/PlantSlabBlock.java
这个类没必要保留，直接把APlantSlabBlock的abstract删掉

2024-03-11 22:50 UTC, Snownee commented on src/main/java/org/teacon/xkdeco/block/APlantSlabBlock.java
> +		return !this.isPath;
下界岩台阶、末地石台阶也没有随机刻

2024-03-12 14:06 UTC, a1640727878 commented on src/main/java/org/teacon/xkdeco/init/XKDecoObjects.java
> +				var block = BLOCKS.register(id, () -> new PlantSlabBlock(properties, isPath, "dirt_slab"));
我感觉还是想想写一个新的注册方法, 现在整个整套都是字符串匹配

2024-03-12 15:19 UTC, Snownee commented on src/main/java/org/teacon/xkdeco/init/XKDecoObjects.java
> +				var block = BLOCKS.register(id, () -> new PlantSlabBlock(properties, isPath, "dirt_slab"));
有计划把这一整个类完全重写，但目前没时间。暂时能用就行

2024-03-13 08:32 UTC, merged